import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import {
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowDownLeft,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Ban,
  Bell,
  Bold,
  BookOpen,
  Building2,
  Calendar,
  Check,
  CheckCheck,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Code,
  CornerUpRight,
  CreditCard,
  Download,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileEdit,
  FileSpreadsheet,
  FileText,
  Filter,
  Flag,
  HelpCircle,
  History,
  Inbox,
  Info,
  Italic,
  Key,
  Landmark,
  LayoutDashboard,
  Link,
  Link2,
  List,
  ListChecks,
  ListOrdered,
  Lock,
  LogIn,
  LogOut,
  LucideAngularModule,
  type LucideIconData,
  Mail,
  MailOpen,
  MailSearch,
  Mails,
  MessageSquare,
  Moon,
  MoreHorizontal,
  Paperclip,
  Pencil,
  PenLine,
  Phone,
  Play,
  Plus,
  Printer,
  Quote,
  Receipt,
  RefreshCw,
  Reply,
  ReplyAll,
  RotateCw,
  Route,
  Save,
  ScrollText,
  Search,
  Send,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Sun,
  Tag,
  Terminal,
  Ticket,
  Timer,
  Underline,
  Upload,
  UploadCloud,
  User,
  UserCheck,
  UserPlus,
  Users,
  X,
  XCircle,
  Zap,
} from 'lucide-angular';

const ICONS: Record<string, LucideIconData> = {
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  archive: Archive,
  'arrow-down': ArrowDown,
  'arrow-down-left': ArrowDownLeft,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  ban: Ban,
  bell: Bell,
  bold: Bold,
  'book-open': BookOpen,
  'building-2': Building2,
  calendar: Calendar,
  check: Check,
  'check-check': CheckCheck,
  'check-circle': CheckCircle,
  'check-circle-2': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  clock: Clock,
  code: Code,
  'corner-up-right': CornerUpRight,
  'credit-card': CreditCard,
  download: Download,
  'edit-3': Edit3,
  'external-link': ExternalLink,
  eye: Eye,
  'eye-off': EyeOff,
  file: File,
  'file-edit': FileEdit,
  'file-spreadsheet': FileSpreadsheet,
  'file-text': FileText,
  filter: Filter,
  flag: Flag,
  'help-circle': HelpCircle,
  history: History,
  inbox: Inbox,
  info: Info,
  italic: Italic,
  key: Key,
  landmark: Landmark,
  'layout-dashboard': LayoutDashboard,
  link: Link,
  'link-2': Link2,
  list: List,
  'list-checks': ListChecks,
  'list-ordered': ListOrdered,
  lock: Lock,
  'log-in': LogIn,
  'log-out': LogOut,
  mail: Mail,
  'mail-open': MailOpen,
  'mail-search': MailSearch,
  mails: Mails,
  'message-square': MessageSquare,
  moon: Moon,
  'more-horizontal': MoreHorizontal,
  paperclip: Paperclip,
  pencil: Pencil,
  'pen-line': PenLine,
  phone: Phone,
  play: Play,
  plus: Plus,
  printer: Printer,
  quote: Quote,
  receipt: Receipt,
  'refresh-cw': RefreshCw,
  reply: Reply,
  'reply-all': ReplyAll,
  'rotate-cw': RotateCw,
  route: Route,
  save: Save,
  'scroll-text': ScrollText,
  search: Search,
  send: Send,
  shield: Shield,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  sparkles: Sparkles,
  sun: Sun,
  tag: Tag,
  terminal: Terminal,
  ticket: Ticket,
  timer: Timer,
  underline: Underline,
  upload: Upload,
  'upload-cloud': UploadCloud,
  user: User,
  'user-check': UserCheck,
  'user-plus': UserPlus,
  users: Users,
  x: X,
  'x-circle': XCircle,
  zap: Zap,
};

@Component({
  selector: 'vq-icon',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [LucideAngularModule],
  template: `
    <lucide-angular
      [img]="lucide()"
      [size]="size()"
      [strokeWidth]="strokeWidth()"
      [class]="cssClass()"
      style="display:inline-flex; line-height:0; vertical-align: middle;"
    />
  `,
})
export class Icon {
  readonly name = input.required<string>();
  readonly size = input<number>(16);
  readonly strokeWidth = input<number>(1.6);
  readonly cssClass = input<string>('');

  readonly lucide = computed<LucideIconData>(() => ICONS[this.name()] ?? HelpCircle);
}
